### ISSUE TITLE
Request/Nice to Have: Starting at last used monitor and using last windows size

### ISSUE THREAD

**Issue by cyberbofh** [WarmedxMints/ODMissionStacker#1]
I've noticed that the OD Massacre Stack Manager always starts on the main screen, with it's default window size

Since I am a multi-monitor user, it would be **nice to have** if the OD Massacre Stack Manager could start at 

- last used monitor
- having it's last window size

CB

**Comment by WarmedxMints** [comment]
No worries.  I've implemented both of those requests for the next update.
