### ISSUE TITLE
conflict zone massacre mission not detected

### ISSUE THREAD

**Issue by netchild** [WarmedxMints/ODMissionStacker#10]
![2022-05-23_09-26-00_Mbutas_Mbutas](https://user-images.githubusercontent.com/3617760/169766625-972e19b8-0844-4cbc-b709-8a3ab855d761.jpg)

Is it supposed to detect this mission (conflict zone target area)? It doesn't if it is.

**Comment by WarmedxMints** [comment]
No, the app doesn't track conflict zone missions since they cannot be stacked like pirate massacre missions due to them only being issued by one faction.
