### ISSUE TITLE
Phantom Missions showing in stack manager.

### ISSUE THREAD

**Issue by SeeJayEmm** [WarmedxMints/ODMissionStacker#13]
I'm having a problem where phantom (maybe?) completed missions are showing up in the stack manager. This is happening in Odyssey and Horizons.  I've checked my transactions as well as the stations in question and I cannot find this missions.

I've reloaded the app.
I've deleted re-read the history.
I've deleted the save data jsons off the disk and then reloaded the history.

The phantom missions keep coming back. I'm not sure if this is an issue with the OD stack manager or ED, honestly.

![image](https://user-images.githubusercontent.com/788552/192930443-63073967-47bb-4e83-a508-0e2da15fd7df.png)

**Comment by WarmedxMints** [comment]
Yes, I suspect there is an issue with the game failing to fire mission redirected and completed events.  If you could zip your logs directory and email it to me, that would be great.  You can send them to warmedmintsstudios@gmail.com.

If you zip the Elite Dangerous folder found in %USERDATA%\Saved Games\Frontier Developments.

Thanks

**Comment by SeeJayEmm** [comment]
Will do.

As an aside I fired up ED Discovery and it does not show the phantom mission(s).

**Comment by WarmedxMints** [comment]
EDD clears missions with the Missions event which fires when you log in.  Hence why if you switch from horizons to odyssey with EDD, you lose the missions for the DLC you were previously loaded into.  I don't clear them at the moment so you can swap DLCs without losing the information on the stack for the other.

I may have to parse through the missions though in that event and check just the ones for whichever DLC you are in.

**Comment by WarmedxMints** [comment]
This should now be fixed with the merging of the live modes.

https://github.com/WarmedxMints/ODMissionStacker/releases/tag/v1.7.2
