### ISSUE TITLE
Suggestion: Hide completed missions

### ISSUE THREAD

**Issue by sassysasquatchstudios** [WarmedxMints/ODMissionStacker#2]
It'd be nice to just hide the completed missions from the list, and/or to have a seperate display of completed, vs active.

**Comment by WarmedxMints** [comment]
Completed missions are moved and are under a different dropdown.   Do you mean the redirected missions?  They are highlighted in a different colour to let you know they are ready to turn in.

**Comment by WarmedxMints** [comment]
I'm going to assume you meant redirected missions and this has now been changed in version 1.4
