### ISSUE TITLE
Discrepancy between Kills Remaining and actual completion

### ISSUE THREAD

**Issue by RanykT** [WarmedxMints/ODMissionStacker#20]
I started using this not to long ago and I'm hitting a dry spell. However, what I'm noticing is an inconsistency between Kills Remaining and that actual completion of the stack. I've had 3 cases in the last week where I was like "wait, didn't I still have more kills left?" But last night, I saw it for certain. I had 14 kills left while I was trying to rush completion, but when I checked after the relog, I was at 0. I killed like 2-3 enemies, yet finished 14? My current running theory is that I put my fighter on Aggresive to kill limpet snipers, which don't give me bounties.

**Comment by WarmedxMints** [comment]
This is down to Elite unfortunately.  I have to guess your progress through the bounty event which it doesn't always write.  It especially bad when you are in a wing.  Unfortuantely, there is no mission updated event for the kills so the app has to take it's best guess.
