### ISSUE TITLE
Automatic History Folder Error(s)

### ISSUE THREAD

**Issue by jmunoz2141** [WarmedxMints/ODMissionStacker#26]
Receiving windows system errors when the application is trying to save certain json folders when affirmatively promting for automatic journal history searching.  When done manually, no history is visible after pointing to the E:D journal history folder.  A print screen of the error is attached.
![Picture1](https://github.com/WarmedxMints/ODMissionStacker/assets/84143412/aba40751-5a9b-4caf-921f-8b6f7f6a5cfa)

**Comment by Lusiphur** [comment]
Bump. Happening for me too. Even when running as admin. Happens on any command within the GUI.

**Comment by simtiaz5** [comment]
Putting the Application Folder in Windows (C:) appears to remedy the solution.

**Comment by WarmedxMints** [comment]
This appears to be down to where you are running the app from.  It requires write permissions to the folder it is in,
