### ISSUE TITLE
App doesn't pick up data

### ISSUE THREAD

**Issue by LudwigIron** [WarmedxMints/ODMissionStacker#5]
Hi there, thanks for this app.

I've downloaded and run v 1.3.  However, no data is pulled.

My logs are not in the usual place.  Steam puts them in

\SteamLibrary\steamapps\common\Elite Dangerous\Products\elite-dangerous-64
\SteamLibrary\steamapps\common\Elite Dangerous\Products\elite-dangerous-odyssey-64

Any advice?  Cheers.

**Comment by WarmedxMints** [comment]
I assume you are running on Windows?

I have not heard of Elite using a different directory and two different directories makes life even harder.  I did find a forum post about problems with permissions, maybe that will help you to get the game using the saved games folder instead.

https://forums.frontier.co.uk/threads/cannot-find-player-journal-log.405782/

I will look into adding an option for a custom log directory though.

**Comment by LudwigIron** [comment]
Yes Windows.

Actually they put them in different locations for different sources
https://customersupport.frontier.co.uk/hc/en-us/articles/4405700513298-Game-installation-and-file-locations-Netlog-AppConfig-Client-Log-Update-Log-Game-Folder-

But thanks.  Looking forward to it.

**Comment by WarmedxMints** [comment]
You are confusing the different types of logs there.  None of those are locations where the player journals are saved, those are for different log files, none of which are used for the app.  

You are looking for the location where it is saving the files named Journal*.*.log files.  

https://customersupport.frontier.co.uk/hc/en-us/articles/4404788337938-Where-can-I-find-the-player-journal-

**Comment by WarmedxMints** [comment]
The option to set a custom journal path has been added in v1.4

**Comment by LudwigIron** [comment]
> The option to set a custom journal path has been added in v1.4

Cheers mate.  That fixed my issue.
