### ISSUE TITLE
EliteJournalReader library version unknown

### ISSUE THREAD

**Issue by Rain0Ash** [WarmedxMints/ODMissionStacker#6]
O7 Commander.
What version of the EliteJournalReader library should be used for compile 1.4?
From nuget it can't find FileheaderEvent.FileheaderEventArgs.Odyssey property.
From your fork - it doesn't contains JournalWatcher.ReadingHistory property and JournalWatcher.ParseHistory method.

Have a good flight!

**Comment by WarmedxMints** [comment]
I forgot to update my for of EJR.  It has been done now.
