### ISSUE TITLE
Feature Request: Make the bottom bar movable up, clips on small screend

### ISSUE THREAD

**Issue by capsel22** [WarmedxMints/ODMissionStacker#9]
Hi,
I'm using iPad mini as an external monitor and have the Stack manager displayed there.
However, the bottom bar clips, since the screen is quite small, and I cant see the details.

If the bar was movable up, that would be fine. Please see picture.
![Screenshot 2022-03-29 075153](https://user-images.githubusercontent.com/38831192/160551351-f28e056a-f5ef-4a5d-bef4-06e7061867eb.png)

**Comment by WarmedxMints** [comment]
I have added a splitter bar so you can adjust the view.  Hopefully, that helps.  Let me know if it does not.

You can find it in v1.5 - https://github.com/WarmedxMints/ODMissionStacker/releases/tag/v1.5

**Comment by capsel22** [comment]
That's amazing, thank you.
